### ISSUE TITLE
Adding a one-click deploy

### ISSUE THREAD

**Issue by phazonoverload** [MichaelJolley/twitch-orbit#1]
Hey! 

Thanks for your work on this integration @MichaelJolley. We were thinking about building something similar but we'd much rather feature this community-built one in our integrations library, if you're happy with that? 

Before we do I wanted to suggest a click-to-deploy option on Heroku so folks who are less technical can still find benefit in what you've built. I'm happy to take on this work if you want?

**Comment by michaeljolley** [comment]
That's a brilliant idea. Feel free to take it on.
